name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: # Permissions for GitHub pages
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.75.0
  NIGHTLY_RUST_VERSION: nightly-2023-10-29
  RUSTFLAGS: -D warnings
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  # rustfmt:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install latest nightly Rust
  #       uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: ${{ env.NIGHTLY_RUST_VERSION }}
  #         components: rustfmt

  #     - name: Rustfmt check
  #       working-directory: ./example
  #       run: cargo +${{ env.NIGHTLY_RUST_VERSION }} fmt --all -- --check

  cargo-verfications:
    runs-on: ubuntu-latest
    # needs:
    #   - rustfmt
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - name: Install latest Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - name: Install cargo-llvm-codecov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Clippy check
        working-directory: ./example
        run: cargo clippy --all-targets --all-features

      - name: Cargo test
        working-directory: ./example
        run: cargo test --all-targets --all-features

      - name: Code coverage report
        working-directory: ./example
        run: cargo llvm-cov --all-features --html

      - name: Checkout the repo again for pushing pages revision
        uses: actions/checkout@v3
        with:
          ref: 'codecov-pages'
          path: 'pages-branch'

      - name: Push codecov report to it's branch
        working-directory: ./pages-branch
        run: |
          git config user.email "2204863+Dentosal@users.noreply.github.com"
          git config user.name "Dentosal"
          cp -r ../example/target/llvm-cov/html ${{ env.GIT_BRANCH }}
          git add .
          git commit -m "Update codecov for ${{ env.GIT_BRANCH }}"
          git push
